version: "2"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/logs:/var/log/nginx
      - ./web:/var/www/katya/web
    ports:
      - 80:80

  katya:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PROFILE=prod
    volumes:
      - ./bot/bin:/home/node/app
      - ./bot/config:/home/node/app/config
      - ./bot/db:/var/katya
    expose:
      - "11000"
    restart: always
    command: "node katya-virt-bot.js"

  name-plugin:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./plugin-def/bin:/home/node/app
    expose:
      - "11001"
    restart: always
    command: "node name-reaction.js"

  weather-plugin:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./plugin-weather/bin:/home/node/app
    expose:
      - "11002"
    restart: always
    command: "node weather.js"

  weather:
    image: openjdk:17
    working_dir: /app
    volumes:
      - ./weather:/app
    expose:
      - "11100"
    restart: always
    command: "java -jar weather-0.0.1-SNAPSHOT.jar"
