version: "2"
services:

  katya:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PROFILE=prod
    volumes:
      - ./:/home/node/app
    expose:
      - "8888"
    restart: always
    command: "node katya-virt-bot.js"

  name-plugin:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./plugins/name-reaction:/home/node/app
    expose:
      - "11001"
    restart: always
    command: "node name-reaction.js"
